name: Run RedEye Bot Automation

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: macos-latest  # Uses latest available macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer # Change 15.4 if needed

      - name: Set up Xcode
        run: sudo xcodebuild -license accept

      - name: Run Automation Bot
        run: xcodebuild test -scheme "Automated RedEye Bot" -destination 'platform=iOS Simulator,name=iPhone 14'
